### ISSUE TITLE
Persisting Data

### ISSUE THREAD

**Issue by pixelyo** [grocy/grocy-docker#1]
in the current [docker-compose.yml](https://github.com/grocy/grocy/blob/be326a5211d35d94ff72857f2a8c6a59d5e7b81d/docker-compose.yml) no [volumes](https://docs.docker.com/storage/volumes/) are being used for persistent data

I think that at least the sqlite db has to be persisted

**Comment by talmai** [comment]
resolved via PR #6

**Comment by Braintelligence** [comment]
@talmai Does this also work with mounted volumes? I couldn't make it work by changing the line to a mounted volume. Doing it as described in the PR works.

**Comment by markusressel** [comment]
@Braintelligence If you want to use a mounted volume you need to copy the contents of `/www` in the grocy container to the persisted volume first. If you are using Kubernetes or Rancher, have a look at this:

https://stackoverflow.com/questions/46389817/kubernetes-share-volume-between-containers-inside-a-deployment
