### ISSUE TITLE
Error starting userland proxy: listen tcp 127.0.0.1:80: bind: address already in use

### ISSUE THREAD

**Issue by Porrumentzio** [grocy/grocy-docker#104]
Running `grocy-docker` on Raspbian, yesterday I was able to build `grocy-nginx`, but not today.
When running `docker-compose up -d` on the directory where I downloaded the sourcecode of this repo (#103), I get this error for nginx:
```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (6e4362d7001bac77a95f14887f4b53733b003f895cfabc4d92d811822ca43c4b): Error starting userland proxy: listen tcp 127.0.0.1:80: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (6e4362d7001bac77a95f14887f4b53733b003f895cfabc4d92d811822ca43c4b): Error starting userland proxy: listen tcp 127.0.0.1:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Does someone know why is this? Seems a misconfiguration on Nginx ports, but I have changed nothing.

**Comment by erikswain** [comment]
I have this issue as well, were you able to resolve it? 
Changing the ports in the docker-compose.yml file to something like  
```
ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8443:8443'
```
fixes the error, but nothing resolves on 8080 or 8443.

**Comment by Porrumentzio** [comment]
I didn't manage to solve it. In fact I shut down the computer/server.

I'll try this. What do you mean that nothing resolves on those ports?

**Comment by Porrumentzio** [comment]
I tried this and I get that Nginx is running well, but nothing is showed

**Comment by erikswain** [comment]
Yea that’s what I’m seeing as well

**Comment by jayaddison** [comment]
Yep, [these lines in the `docker-compose.yml`](https://github.com/grocy/grocy-docker/blob/ac89672bc9895d69497cb311745f5648b2eada0c/docker-compose.yml#L15-L16) state that the container ports (8080 and 8443) should be exposed by the Docker service at localhost (127.0.0.1) ports 80 and 443.

When the `80: bind: address already in use` error crops up, that likely indicates that another service is already bound to TCP port 80.  Is there a chance another web server (like Apache or Nginx) is already running on the system where you're running `docker-compose up`?

One command you could try to check whether any other processes are already listening on TCP 80 is:

```
# NB: may need to run this with superuser privileges
$ lsof -i TCP:80 -s TCP:LISTEN
```

**Comment by jayaddison** [comment]
Closing this since there's not yet enough information to indicate this is a problem within `grocy-docker`.  Please let me know if you uncover more details to indicate that it is.

**Comment by Porrumentzio** [comment]
Using the default configuration on Raspbian with docker results that `docker-nginx` container can not be built.
This is the output to this command

```
sudo lsof -i TCP:80 -s TCP:LISTEN
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx   1581     root    6u  IPv4  16546      0t0  TCP *:http (LISTEN)
nginx   1581     root    7u  IPv6  16547      0t0  TCP *:http (LISTEN)
nginx   1583 www-data    6u  IPv4  16546      0t0  TCP *:http (LISTEN)
nginx   1583 www-data    7u  IPv6  16547      0t0  TCP *:http (LISTEN)
nginx   1584 www-data    6u  IPv4  16546      0t0  TCP *:http (LISTEN)
nginx   1584 www-data    7u  IPv6  16547      0t0  TCP *:http (LISTEN)
nginx   1585 www-data    6u  IPv4  16546      0t0  TCP *:http (LISTEN)
nginx   1585 www-data    7u  IPv6  16547      0t0  TCP *:http (LISTEN)
nginx   1586 www-data    6u  IPv4  16546      0t0  TCP *:http (LISTEN)
nginx   1586 www-data    7u  IPv6  16547      0t0  TCP *:http (LISTEN)
```

Does someone know interpreting this?
