### ISSUE TITLE
Build docker images for multiple architectures

### ISSUE THREAD

**Issue by jayaddison** [grocy/grocy-docker#105]
We currently build `amd64` images for `grocy-docker`.  It'd be worth building multi-architecture images.  This might raise questions about the OS images and libraries we're using, since it's possible that some of them contain architecture-specific compiled code.

**Comment by Porrumentzio** [comment]
Oh, so maybe some problems that I'm having on ARM architecture are for this. I'll be watching, and say me if you want me to test something on ARM

**Comment by jayaddison** [comment]
The `buildah-build` GitHub Action by Red Hat now features support for the `manifest` feature -- allowing composition of images that contain support for multiple different architectures.

That might make this feature easier to achieve.

See https://github.com/redhat-actions/buildah-build/issues/61
