### ISSUE TITLE
"Connection reset" when run on Synology NAS

### ISSUE THREAD

**Issue by Zeklandia** [grocy/grocy-docker#108]
This is my first time self-hosting grocy. I used Docker's Synology app to download the grocy image and create a container, then configured the volume and network settings as instructed. When I try to connect to grocy, I get an error saying the connection was refused. I have never used Docker before, but online it seems this is a configuration issue with Docker that I don't even think the Synology app gives me enough control to fix.

```
$ docker container ls
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                          NAMES
744fa94507e9        grocy/grocy:v2.7.1-4   "php-fpm7"          About an hour ago   Up 4 seconds        0.0.0.0:9000->9000/tcp, 0.0.0.0:8001->80/tcp   grocy
```

**Comment by Zeklandia** [comment]
I also tried making a container that was set to run on the same network as the host. Same result.

**Comment by Zeklandia** [comment]
The connection needs to be to the container running the image grocy/nginx, not grocy/grocy.

**Comment by jayaddison** [comment]
Thanks @Zeklandia - I don't have access to a Synology device; do you know how it determines which container to create the connection to, and/or does that have to be manually specified?

If we can find a way to set the `grocy/nginx` container as the preferred default (possibly via `docker-compose.yml` configuration) then that could be a nice small improvement.

**Comment by Zeklandia** [comment]
> Thanks @Zeklandia - I don't have access to a Synology device; do you know how it determines which container to create the connection to, and/or does that have to be manually specified?

There's a menu for selecting which ports to froward between the container and the local network. I kept trying to use the `grocy` container, which would always refuse connections. As I have it set right now, there are two ports on the `grocy/nginx` container (`http` and `https`) and none on the `grocy` container. Both are on the Docker `bridge` network, so in the `grocy/nginx` container's settings, I added a link to the `grocy` container to make sure they could communicate. I don't know if that's necessary, but it works.

> If we can find a way to set the `grocy/nginx` container as the preferred default (possibly via `docker-compose.yml` configuration) then that could be a nice small improvement.

The first problem I had was that I didn't realize that grocy needs a grocy/nginx container. The Docker Hub search tool on Synology does a very simple keyword search, with results ordered by popularity, so searching "nginx" or "grocy nginx" yield the same thousands of images. Fortunately, `grocy/nginx` isn't too far down the list. But I only found this out when I came across an explanation that I think you have to someone when they posted the output of a Docker command and it was pointed out that they only had one running container, and no `grocy/nginx` container. I had to manually set up both containers (I don't think there's a package dependency system to fix this), but once I did it worked right away.

The guide definitely needs to be updated to make it clear how to set up both containers.

**Comment by jayaddison** [comment]
@Zeklandia Thanks a lot for the explanation, that helps get a sense of what's going on.  From your message here's what I understand so far:

- The interface offered by the Synology device provides search & installation of individual containers
- The `grocy/grocy` application container appears prominently for searches on the term `grocy`, but the `grocy/nginx` image appears lower down (and isn't clearly associated with `grocy/grocy`)
- The required `grocy/nginx` container is not installed automatically as a dependency of the `grocy/grocy` application container

It may take a little while but hopefully we can find a way to improve this; I'll plan to do some research soon.

It'd also be great to find out whether the bridge network is required between the two containers; I'd appreciate any help looking into that, but don't want to ask anything that could potentially break a running system, so please consider that an optional investigation :)

**Comment by Zeklandia** [comment]
> @Zeklandia Thanks a lot for the explanation, that helps get a sense of what's going on.  From your message here's what I understand so far:
> 
> - The interface offered by the Synology device provides search & installation of individual containers

[This userguide](https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/docker_container) shows what the process looks like.

> - The `grocy/grocy` application container appears prominently for searches on the term `grocy`, but the `grocy/nginx` image appears lower down (and isn't clearly associated with `grocy/grocy`)

Yes. I can't check at the moment, but I'm fairly certain that `grocy/nginx` does not appear in the results for "grocy" at all.

> - The required `grocy/nginx` container is not installed automatically as a dependency of the `grocy/grocy` application container

Correct.

> It may take a little while but hopefully we can find a way to improve this; I'll plan to do some research soon.

Thank you for your enthusiasm. It's not bad as it is, it's just a couple more steps than expected.

> It'd also be great to find out whether the bridge network is required between the two containers; I'd appreciate any help looking into that, but don't want to ask anything that could potentially break a running system, so please consider that an optional investigation :)

The other option is to run them on the host's network interface. This eliminates the need for port forwarding the containers themselves. I will test this when I get back, but it should work.
