### ISSUE TITLE
Bug: missing packages for Grocy v.3.0.0

### ISSUE THREAD

**Issue by jeauxlb** [grocy/grocy-docker#112]
Hi,

To use LDAP and EXIF packages currently contained in Grocy v3.0.0, the docker image requires additional packages not currently installed during the build. The system dependencies statement should look like the following:
```
# Install system dependencies
RUN     apk add --no-cache \
            php7-ctype \
            php7-fpm \
            php7-fileinfo \
            php7-iconv \
            php7-json \
            php7-gd \
            php7-pdo_sqlite \
            php7-simplexml \
            php7-tokenizer \
            php7-ldap \
            php7-exif
```

**Comment by jayaddison** [comment]
Thanks @jeauxlb!  This should be resolved by #114; I'll merge that soon.  It might be nice to wait for #111 to merge first so that we can test out an automated release process for this.

**Comment by jayaddison** [comment]
@jeauxlb This should be solved in the latest tagged Docker Hub container images (`grocy/grocy:v3.0.0-2`) - let me know if & when you're able to confirm that; glad to investigate further if there are still problems.

**Comment by jeauxlb** [comment]
Hi, confirming that the LDAP packages work, so assuming the EXIF stuff does too. Thanks for the quick update.
