### ISSUE TITLE
Permissions Request: grocy-docker

### ISSUE THREAD

**Issue by jayaddison** [grocy/grocy-docker#113]
Hi @berrnd - happy new year!  Could you grant me `admin` permissions to the `grocy-docker` repository, for the purpose of configuring [GitHub encrypted secrets](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository)?  These will be used to automate Docker Hub image builds (as being configured in #111).

**Comment by berrnd** [comment]
Sure, is done.

Happy 2021. 🥂🍀
