### ISSUE TITLE
Docker Hub 'latest' tag pushed, however versioned tag does not exist?

### ISSUE THREAD

**Issue by jayaddison** [grocy/grocy-docker#117]
Currently at https://hub.docker.com/r/grocy/grocy/tags:

- the `latest` tag is listed
- the intended `v3.0.1-2` tag corresponding to the latest automated build & push is not latest

Perhaps the build and release workflow needs to be updated to push additional tags.

**Comment by jayaddison** [comment]
cc @BitFis - don't suppose you've seen this behaviour before from `docker-compose`?

The build tagged the images with the correct version in the build logs ([`grocy/grocy:v3.0.1-2` here](https://github.com/grocy/grocy-docker/runs/1708152821#step:6:67) and [`grocy/nginx:v3.0.1-2` here](https://github.com/grocy/grocy-docker/runs/1708152821#step:6:135)), but Docker Hub doesn't seem to have had versioned tags pushed to it (only `latest`).

**Comment by BitFis** [comment]
yea, seems like we need to write `GITHUB_API_TOKEN='***' GROCY_IMAGE_TAG="$(git describe --abbrev=0 --tags) docker-compose push`, then it should work

**Comment by jayaddison** [comment]
Ah, I see - so the image names during `docker-compose push` are (re)read from the `docker-compose.yml` file, and so we need to pass the environment variables in again.  That seems consistent, thanks.  I'll update that soon.

**Comment by BitFis** [comment]
I was not aware of that eather, but makes sence, since the variables are not declared on the second run, we maybe could think about setting those variables as environemnt variables.

**Comment by BitFis** [comment]
also, it might be usful to lush all smeantic version parts, aka. latest / v3 / v3.0 / v3.0.1 / v3.0.1-2, what do you think? Allowing for semantic versioned automated updates

**Comment by jayaddison** [comment]
Regarding environment variables: yep, that would be the cleanest solution I think.  For now I'm testing a change with the variable duplicated across the build and push steps.

Pushing partial versions might also make sense too, yep, let me think about that.  To some degree I like that there is a one-to-one unambiguous mapping between a container image, the version number, and the corresponding code.  But it's worth considering since people do often like to pin/specify their container versions using partial version prefixes.

**Comment by jayaddison** [comment]
That seems to have worked - the latest image is now pushed.

**Comment by jayaddison** [comment]
> That seems to have worked - the latest image is now pushed.

To clarify this, after-the-fact.. I meant that the 'most recent version' of the container image had been pushed to Docker Hub, _not_ that an image with the `latest` tag had been pushed.

It did turn out that a stale/broken image with the `latest` tag was still present however, as surfaced in #120.  That has now been removed.
