### ISSUE TITLE
Calendar tab showing 502 Bad Gateway

### ISSUE THREAD

**Issue by crixster** [grocy/grocy-docker#118]
Everything seems to work except the calendar. I get 502 Bad Gateway page instead. Any ideas? The following is the stack i am running on a raspberry pi4

---
version: "2.1"
services:
  grocy:
    image: linuxserver/grocy:arm32v7-latest

    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Asia/Kuala Lumpur'
    volumes:
      - /Kingston_240GB/grocy/:/config
    ports:
      - 9283:80
    restart: unless-stopped

**Comment by crixster** [comment]
lol it turns out i had to add a chore in master data first. Guess that solved the problem

**Comment by jayaddison** [comment]
Thanks @crixster - it looks like this has affected a few folks.  Glad to hear that applying some updates to the database provided a fix.  I'll aim to investigate further soon, and will re-open this issue because we may be able to avoid these HTTP 502 errors occurring in a fresh container environment.

**Comment by jayaddison** [comment]
@crixster Can you share the version of the `docker-grocy` container image you were using when you encountered this HTTP 502 error?  (`docker ps -a` can provide this for a running docker instance, I think)

**Comment by jayaddison** [comment]
It sounds like this was resolved; please let us know if you see this happening again and/or can provide additional details.

**Comment by crixster** [comment]
> It sounds like this was resolved; please let us know if you see this happening again and/or can provide additional details.

So sorry for the extremely late reply. As for today here is the Grocy version i am using as per the screenshot. As for the docker image i am using linuxserver/grocy:arm32v7-latest running from a rpi4 4gb variant. It was a small issue and so far i don't encounter any further errors. Thanks for the support and i really apologize for the late reply

![Screenshot_20210210_160444_com duckduckgo mobile android](https://user-images.githubusercontent.com/32066057/107482024-111af300-6bba-11eb-8b05-16cf9f80e99b.jpg)
