### ISSUE TITLE
Missing node_modules folder in grocy/grocy image

### ISSUE THREAD

**Issue by ThaChillera** [grocy/grocy-docker#120]
When setting up this container the node_modules folder was never populated for some reason.

Solved by manually running npm install in /var/www, and copying /var/www to /var/www/public.

Not sure if this docker is unmaintained or I did something horribly wrong, but it ended up working :)

**Comment by jayaddison** [comment]
Thanks for the report @ThaChillera - could you confirm what version of the container you were using, and whether you were building it from source or using an existing image?

**Comment by ThaChillera** [comment]
Using grocy/grocy:latest, from the docker hub. added it to my own reverse proxy that also serves other projects, so I didn't use the grocy/nginx but used this git as the example

**Comment by jayaddison** [comment]
Thanks @ThaChillera; this seems to have been a bug/issue related to https://github.com/grocy/grocy-docker/issues/117.  I've removed the tag and if you try the versioned container images (for example, `grocy/grocy:v3.0.1-8` and `grocy/nginx:v3.0.1-8`) you should find better results.

I was surprised to find that there was a `latest` tag present at all; that's not generally what is expected at the moment.  I've added a task to the list at https://github.com/grocy/grocy-docker/issues/109 to look into this again in future.

**Comment by jayaddison** [comment]
I'm closing this issue for now, but feel free to add any more details, especially if you run into further problems related to this.

**Comment by ThaChillera** [comment]
> I'm closing this issue for now, but feel free to add any more details, especially if you run into further problems related to this.

I tried both the tags v3.0.1-8 (as the latest version) and v2.7.1-5 (as the version I want to run (using the android app which doesn't support v3 yet)). Both have the exact same issue, with an uninitialized packages.json. The weird thing is, nowhere in this repository is any reference to npm (which is used to create the node_modules folder) except in the documentation on how to run a vulnerability scan.

How exactly is a fresh image supposed to get the node_modules folder? cause I don't see how it gets it.

**Comment by jayaddison** [comment]
Thanks @ThaChillera - I'll try to look into this soon.

The `node_modules` directory should be populated by `yarn` here: https://github.com/grocy/grocy-docker/blob/f2cd18628ee9946925352d750f4f1393b071efbe/Dockerfile-grocy-nginx#L54-L56

**Comment by ThaChillera** [comment]
Aaaah, that explains everything - I didn't know yarn could populate node_modules. I'm not running grocy/nginx just grocy/grocy, which seems to try the same thing with a different program: https://github.com/grocy/grocy-docker/blob/main/Dockerfile-grocy#L62

I think that step is failing for some reason

**Comment by jayaddison** [comment]
@ThaChillera Cool, gotcha.  `grocy/nginx` and `grocy/grocy` are designed to work side-by-side; static web content is in the `nginx` image, and PHP code is in the `grocy` image.

That `composer` step is similar to `yarn` / `npm` in that it is a package manager, yep.  Sometimes rate limiting or network failures can occur there, so that'd be one possibility to investigate in your build logs.  Interested to hear the cause if & when you find it, whatever it is.

As an aside: perhaps `grocy/nginx` should be renamed to something more meaningful, to make that clearer (`grocy/www`?).

**Comment by jayaddison** [comment]
@ThaChillera Could you rename this issue to "Missing node_modules folder in grocy/grocy image", now that we have a shared understanding?

**Comment by ThaChillera** [comment]
Hi @jayaddison , I returned after some months to update to grocy 3.0.1, and saw some nice improvements! however, there still is a dependency between the two Dockerfiles in their current form, which goes against the Docker ethos (make it do one thing, and do it independently)

I'd say there is real value in splitting these dockerfiles, with the grocy container serving the server files via a volume to the nginx container. This can be easily done by adding `Volume ["/var/www"]` to the grocy Dockerfile. Just the grocy Dockerfile could populate the node_modules folder, and this issue would be resolved.

A separate but related issue is the data volume: it's defined in the Dockerfile, but setting it bind mount/local folder (as I like to do) wipes the folder, since `Volume` is only compatible with docker volume mounts, not bind mounts. This could be resolved by populating the data folder after container initialization, after an `is folder empty` check.

Let me know if you agree with these steps forward, I have some more time on my hands (and already implemented the first suggestion) so am more than willing to help out!

**Comment by aTable** [comment]
Maybe this will help someone else or future me. I had an issue where my rpi3 docker-compose was giving:

```
grocy               | [cont-init.d] 50-config: executing...
grocy               | mv: inter-device move failed: '/defaults/node_modules' to '/app/grocy/public/node_modules/node_modules'; unable to remove target: Directory not empty
grocy               | [cont-init.d] 50-config: exited 0.
```
that resulted grocy running but with many unavailable javascript libraries (toastr, tempusdominus-bootstrap-4, ...) 404ing. I brute forced a fix by 

```
docker exec -it grocy /bin/bash

cp -r  /defaults/node_modules/toastr /app/grocy/public/node_modules/
cp -r  /defaults/node_modules/tempusdominus-bootstrap-4 /app/grocy/public/node_modules/
```
