### ISSUE TITLE
Pi Image for Grocy

### ISSUE THREAD

**Issue by highaltidude** [grocy/grocy-docker#121]
Love this project first of all! Got a little one on the way and can't wait to use this to it's fullest.

Has there been any talks of creating a Pi Image for this? I'd love to assist in setting this up. I got my instance running on a Pi but for someone with little experience this would be tough.

**Comment by RickCoxDev** [comment]
FYI. I've tried the latest image from linuxserver and I've faced issues, without much support from their team. I'd be willing to look into converting this build process to support multiple architectures and opening a PR.

**Comment by jayaddison** [comment]
Closing as resolved by #156 - `grocy-docker` images published to Docker Hub are now multi-architecture.
