### ISSUE TITLE
Consider renaming Dockerfiles to *.Dockerfile because currently syntax highlighting doesn't work by default

### ISSUE THREAD

**Issue by quentincaffeino** [grocy/grocy-docker#126]
If that's fine I'm up to opening a pr.

Also current approach might be preventing other editor extensions from working.

~~**Edit:**
Although this might be useless since it would be better to mash both Dockerfiles together using build targets and leave only single Dockerfile.~~

**Comment by quentincaffeino** [comment]
VS Code, Intelij Idea

**Comment by jayaddison** [comment]
Yep, good thoughts.  Manual adjustment isn't ideal.  VSCode seems to use mime types as one method to detect syntax, and has included support (as shown in [unit tests](https://github.com/microsoft/vscode/blame/e0a52df169572c128b797f81e6f8f80375efac9b/src/vs/base/test/common/mime.test.ts#L30-L35)) to match filename patterns (not just endings) like `Dockerfile-*` for some time.

It looks like IntelliJ's [`FileTypeDetector`](https://github.com/JetBrains/intellij-community/blob/25981a406ba9363af044ca19a877f17762ace29d/platform/core-api/src/com/intellij/openapi/fileTypes/FileTypeRegistry.java#L152) interface makes similar functionality available to plugins.

**Comment by quentincaffeino** [comment]
Very strange that it isn't picked up automatically for me then. Maybe it's only me, then issue is invalid.

**Comment by jayaddison** [comment]
I don't think you've done anything wrong @quentincaffeino, and I'd still conder this a valid issue report.

It looks like VSCode _supports_ detection of syntax based on filename pattern -- and does include unit test coverage related to `Dockerfile` filenames (the link I shared) -- but it doesn't actually do `Dockerfile` syntax matching, at least in the commonly-distributed version of VSCode without any plugins installed.

If you feel like it, the VSCode source itself is open; perhaps it'd be possible to figure out how and where this functionality could be added.

**Comment by quentincaffeino** [comment]
I'm actually fine with how it is now with VSCode (Jetbrains, and maybe others), for me it totally makes sense since I would always write a file extension at the end of the file name and I consider Dockerfile to be a file extension (I would find it weird if someone would write yaml.docker-compose).

But if you want to leave it as is in this repo that is totally, fine I get it.
