### ISSUE TITLE
Bug: Minor. Tag 'latest' missing from Docker repo.  Affects README and default docker-compose.yml

### ISSUE THREAD

**Issue by MichaelTiernan** [grocy/grocy-docker#129]
A docker pull using `docker pull grocy/nginx` defaults to `grocy/nginx:latest` but `latest` as a tag does not resolve.

~~~
docker pull grocy/nginx
Using default tag: latest
Error response from daemon: manifest for grocy/nginx:latest not found: manifest unknown: manifest unknown
~~~

**Comment by jayaddison** [comment]
@MichaelTiernan Thanks for the issue report.  Using the `latest` tag can introduce some unexpected problems, including a few described in https://vsupalov.com/docker-latest-tag/ .  What do you think the tradeoffs would be for introducing it into `grocy-docker`?

**Comment by MichaelTiernan** [comment]
Then your docs should show a tag specifically because on docker hub, the pull command states `docker pull grocy/nginx` which defaults to `docker pull grocy/nginx:latest` it seems which means the pull fails.

Is it right or wrong to use 'latest'? Dunno. I just know it's a default expectation by the underlying system and the users.

**Comment by Mebus** [comment]
Alright folks,

how can I fix this to get Grocy running? I get these erros:

```
root@containers /var/docker/grocy-docker (git)-[main] # docker-compose pull
Pulling grocy ... error
Pulling nginx ... error

ERROR: for grocy  manifest for grocy/grocy:latest not found: manifest unknown: manifest unknown

ERROR: for nginx  manifest for grocy/nginx:latest not found: manifest unknown: manifest unknown
ERROR: manifest for grocy/grocy:latest not found: manifest unknown: manifest unknown
manifest for grocy/nginx:latest not found: manifest unknown: manifest unknown
```

Mebus

**Comment by jayaddison** [comment]
Hi @Mebus @MichaelTiernan - the least-controversial solution is probably one of the ideas mentioned in #109: that we could/should upload `grocy/grocy` and `grocy/nginx` images with the `latest` tag applied when we publish updated releases.

I'll soon make some small edits to the `docker-compose.yml` file and README to try to improve -- or at least clarify -- the situation here.

So far I haven't felt like using the `latest` tag is a great solution.  When people rely on the `latest` tag for any container image, they may receive unexpected updates.  Most updates are good, sure, but sometimes it can be important to make a conscious and considered decision to upgrade.

Unfortunately I have less time for maintenance here nowadays; if anyone feels like suggesting tagging of images with the `latest` tag, I'd be happy to review those (and they could be a sign of interest from potential future maintainers).

**Comment by MichaelTiernan** [comment]
> a few described in

{OPINION:Personal}
The issue s/he is describing is a procedural problem and it strikes me that s/he was having a bad day and railed against people not updating the ':latest' tag.

I agree it's a problem when these shortcomings/artifacts are encountered but I don't believe that it's a reason to abandon the practice outright. I'm of the "Don't like it? Change it or put up with it." school. (Yes, I got beat up a good bit.) ;)
(And just for the record, no I don't like the reliance on "latest" as a tag per se.)

I think (but have no proof) that the issue can be easily addressed in procedures and the /occasional/ failing of those procedures should be considered the price paid as opposed to not following this "convention" and having /all/ procedures fail.

Other than this, I don't know what to say. It is ultimately your choice(s). My only caveat is to document it /*clearly*/ and /*consistently*/

{/OPINION}

Thanks for listening and for your software!
