### ISSUE TITLE
Docker compose failures.

### ISSUE THREAD

**Issue by MichaelTiernan** [grocy/grocy-docker#130]
Attempting to evaluate this project, I began to follow the instructions provided and found two issues:

1. The README misses two steps under "Quickstart":  
```sh
-> git clone https://github.com/grocy/grocy-docker.git
-> cd grocy-docker
docker-compose pull
docker-compose up
```

2. The actual 'compose' process fails after "Step 23/23" in the `Dockerfile-grocy-nginx`  
~~~
Step 23/23 : CMD ["nginx", "-g", "daemon off;"]
---> Running in 28e8abf4e22f
Removing intermediate container 28e8abf4e22f
---> e5a43621c215

Successfully built e5a43621c215
Successfully tagged grocy/nginx:latest
WARNING: Image for service nginx was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating grocy ... done
Creating nginx ... done
Attaching to grocy, nginx
nginx    | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
grocy    | [04-May-2021 18:52:41] ERROR: failed to open configuration file '/etc/php7/php-fpm.d/zz-docker.conf': Permission denied (13)
grocy    | [04-May-2021 18:52:41] ERROR: Unable to include /etc/php7/php-fpm.d/zz-docker.conf from /etc/php7/php-fpm.conf at line 440
grocy    | [04-May-2021 18:52:41] ERROR: failed to load configuration file '/etc/php7/php-fpm.conf'
grocy    | [04-May-2021 18:52:41] ERROR: FPM initialization failed
grocy exited with code 78
nginx exited with code 1
~~~

I had attempted to sort it out but I'm unqualified.

**Comment by jayaddison** [comment]
Puzzling; thanks for reporting this.  I'll plan to take a look next weekend (2021-04-08).

**Comment by jayaddison** [comment]
@MichaelTiernan Hrm.  I'm having trouble recreating the situation and error you're seeing (particularly from the `nginx: [emerg] open()` log line onwards.

Could you try this on another system and see whether you experience the same problem, and then try to narrow down the differences from there?  Or alternatively share a few more details here about the OS and environment you're using, if you're comfortable with that?

**Comment by MichaelTiernan** [comment]
I'm finally getting back to things...
i'll give it a try shortly.
Failure was on a kubuntu system, I'll try it on another now.

**Comment by MichaelTiernan** [comment]
Ah. Found the problem.

There's an assumption of file modes that isn't verified or modified.

Solution was to open the modes on the directory tree:
~~~sh
find * -type d -exec chmod a+rx,go-w "{}" \;
find * -type f -exec chmod a+r,go-w "{}" \;
~~~

**Comment by MichaelTiernan** [comment]
Sorry, that's in the build environment.
I did a `git clone`, then have to do the find with the chmod's before building it.
And thanks for all our work!

**Comment by jayaddison** [comment]
Thanks @MichaelTiernan!  It sounds like you've figured the problem out, so I'll close this issue for now.
