### ISSUE TITLE
Authenticating Grocy Securely and Integration with Barcode Buddy

### ISSUE THREAD

**Issue by MetaBliss** [grocy/grocy-docker#132]
I have a Synology NAS with Docker installed. I use the Portainer container to manage my containers using a graphical GUI and its pretty powerful in all the things it can modify. I had some questions on properly authenticating and fully integrating Grocy and Barcode Buddy with my setup. I have installed Grocy and Barcode Buddy already, on the same docker compose file and both run as intended.

I use the Authelia container (for single sign on and 2FA) in front of a reverse proxy (Nginx Proxy Manager) and use that to control access to my apps. I see that Grocy has a setting in the config file. I just want to make sure its as secure as possible with my setup.

I have the following settings related to authentication:

- DISABLE_AUTH -> False
- AUTH_CLASS -> Grocy\Middleware\ReverseProxyAuthMiddleware
- REVERSE_PROXY_AUTH_HEADER -> REMOTE_USER

My questions are as follows:

1. Is my setup of putting Authelia (with 2FA) in front of NPM proxy to Grocy the most secure way to have it running? Or are there other best practices to follow?

2. For Grocy's AUTH_CLASS variable, I saw LDAP as an option. I have an LDAP server running on my Synology that the Authelia container leverages. What is the difference between using the LDAPAuthMiddleware vs the ReverseProxy one? I think for Authelia, the ReverseProxy one should be used and thats mysetup currently but I could be wrong and wanted to triple check my set up is secure. If there's ways for me to test the security of my setup do let me know. :)

3. Using the above setup, when I login to Authelia, it takes me into Grocy directly without logging in (which I think is how its supposed to work?). However, without the authentication, there is no "Manage API Keys" option in the Grocy Settings panel. Why is that? Is API keys not needed when using Authelia as a Reverse Proxy? Would I not need an API key to connect Grocy with Barcode Buddy? That takes me to my final question...

4. Is there a need for Barcode Buddy or can Grocy do everything? I'd rather drop a container from my stack if there's redundancies. If not, then I would like to integrate Barcode Buddy into Grocy in a seamless way. One thing I notice right now is when I use the Barcode buddy app, when I scan any item I get a JSON error...so some troubleshooting assistance would be super appreciated.

Thank you so much in advance for your help! I have cross posted this to r/grocy as well, whichever would be the most appropriate place to discuss this.

**Comment by jayaddison** [comment]
Hi @MetaBliss - apologies for the delayed response; see below regarding your questions:

1. The configuration you have sounds sensible - those aren't technologies I'm familiar with, but the principles seem reasonable.  As with any other software, try to keep them up-to-date and maintain the ability to restore-from-backup (and change password/login method) in case you become concerned.

2. Again I'm not familiar with those components, but I think that the difference here would be that with ReverseProxy auth, login checks are performed "before" requests reach Grocy -- that is, by the Synology device -- whereas with the LDAP integration, Grocy will receive your login credentials and then contact the Synology LDAP server to authenticate them.  Neither approach is necessarily more secure than the other, but you're correct to want to understand your configuration.

3. This was a bug as reported in grocy/grocy#1462 and has been resolved.

4. I can't provide much guidance here, but I'd recommend searching existing bugtrackers to see whether you can find existing reports of that error, and comparing the data entry workflows between native Grocy and any additional application(s) you're using.
