### ISSUE TITLE
Server returning 403 Forbidden and "File not found"

### ISSUE THREAD

**Issue by d-Rickyy-b** [grocy/grocy-docker#14]
I try to access the (freshly downloaded) application under a subdomain like this: `https://grocy.example.com`. Sadly I only get a 403 Forbidden error. 
![grafik](https://user-images.githubusercontent.com/5798157/53696097-fa5fa500-3dc3-11e9-89c8-9d2061df8214.png)

The `database` folder only contains an **empty** folder called `public`.

Using curl on localhost / from inside the container leads to the same results.

```bash
root@host:/opt/grocy# curl localhost:5002
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>
root@host:/opt/grocy# curl localhost:5002/stockoverview
File not found.
root@host:/opt/grocy# curl localhost:5002/stockoverview/
File not found.
```

`docker-compose logs` returns this:
```
root@host:/opt/grocy# docker-compose logs
Attaching to grocy-nginx, grocy
grocy          | [03-Mar-2019 13:34:38] NOTICE: fpm is running, pid 1
grocy          | [03-Mar-2019 13:34:38] NOTICE: ready to handle connections
grocy          | 172.20.0.3 -  03/Mar/2019:13:34:41 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:34:43 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:34:43 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:51:33 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:52:45 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:53:06 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:53:27 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:53:32 +0000 "GET /index.php" 404
grocy          | 172.20.0.3 -  03/Mar/2019:13:53:43 +0000 "GET /index.php" 404
```

Do you have any idea how to get it running?

**Comment by talmai** [comment]
Can you test against the latest images?

You attempt to load https://localhost and nothing shows up?

**Comment by d-Rickyy-b** [comment]
Apart from the [issues](https://github.com/grocy/grocy-docker/issues/12) I still have with building the container, this seems to work fine now.

I used `docker-compose pull && docker-compose up -d` instead of building the container.

Thank you.

**Comment by ddr2108** [comment]
Do you remeber what the issue was? I'm getting this same issue
