### ISSUE TITLE
How upgrade from version 2.7.1?

### ISSUE THREAD

**Issue by basaandewiel** [grocy/grocy-docker#140]
I tried to upgrade my previous docker version of Grocy (2.7.1).
Running docker-compose pull in current docker-grocy directory gives "Couldn't find env file ... grocy.env

**Comment by jayaddison** [comment]
Hi @basaandewiel - I think it'll be possible to provide you with some guidance for this, and I'll try to write that up as documentation too.

Could you confirm whether you've taken a backup of your existing Grocy 2.7.1 data before getting started?

**Comment by basaandewiel** [comment]
Thanks for your reply. I was running version 2.7 on my Raspberry PI. I tried to build your docker image, and found out that is was not compatible with the ARM HF platform. That made me switch to a docker image compatible with ARM HF. And now everything works fine (and yes I always make a back-up :) )

**Comment by jayaddison** [comment]
Great to hear all that, thanks @basaandewiel :)
