### ISSUE TITLE
How to access config file

### ISSUE THREAD

**Issue by Shadocvao** [grocy/grocy-docker#150]
Hi,

I have tried to access the Grocy config.php file without any luck after installing Grocy with Docker. Please could somebody help me out with the command?

Many thanks!

**Comment by jayaddison** [comment]
Hi @Shadocvao - apologies for the delayed response here.  Are you using `docker` from the command-line to start, stop and manage your containers, or some other tool(s)?

Roughly speaking, I think what you want to do is to stop the application, find the location of the `docker volume`, and then to open and edit the `config.php` that you should find in there.  Please take backups before making changes.

**Comment by jayaddison** [comment]
Closing - please feel free to reopen if you need more help with this.
