### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by barbax7** [grocy/grocy-docker#157]
I updated to 3.1.3 version from 3.1.2
I stopped and removed previeous container, pulled down from github and then executed commands in readme file. On terminale, containers are named with 3.1.3 version, but on grocy website the version is still 3.1.2

![image](https://user-images.githubusercontent.com/66796758/144717603-e5b25151-1f7d-4e6a-8fa4-b6eacbae6c50.png)

The only edits I made are [here](https://github.com/barbax7/grocy-docker/commit/f6d4c24c34c1806ad8cfe0f37632abffe66970f2), one doesn't work but I don't think it can create this issue

**Comment by jayaddison** [comment]
Ciao @barbax7!  Thanks for the report - I ran a check to see what version of the app is listed in the v3.1.3-0 container on Docker Hub:

```sh
$ podman pull docker.io/grocy/backend:v3.1.3-0
$ podman run -it grocy/backend:v3.1.3-0 /bin/sh
$ cat version.json 
{
	"Version": "3.1.3",
	"ReleaseDate": "2021-11-14"
}
```

Could you inspect `version.json` in your local container to see what's in there?

(similar for Docker would be: `docker run -it <container-name> /bin/sh`, I think)

**Comment by barbax7** [comment]
Hi, thanks for your reply
I've executed the command you had suggested, and this is the `version.json` file:
```
{
        "Version": "3.1.2",
        "ReleaseDate": "2021-09-27"
}
```

**Comment by barbax7** [comment]
I deleted all docker images present in my machine, and tried to pull them again
i don't know why but it doesn't download anything... `docker images` returns empty list

**Comment by barbax7** [comment]
Hello

I solved the issue: the problem was in how I edited the `Dockerfile-grocy-frontend` file.
Now it works and i have still the datas, of course.

Thank you for your time

**Comment by jayaddison** [comment]
You're welcome - glad to hear you were able to find and fix the problem.

If you think other people are likely to get stuck on the same / similar issues, feel free to send some suggestions to make that less likely (maybe we can add more documentation, or adjust the file/versioning structure somehow).

**Comment by barbax7** [comment]
My problem was in consequence of this one #153 
I edited `Dockerfile-grocy-frontend`, adding ```
RUN mkdir /var/www/data
COPY custom_js.html /var/www/data/
```, in order to copy a `custom_js.html` inside the container while it is being created. 
So, that command was getting in conflict with regular installation of grocy

Then, I simply entered in the container and created the `custom_js.html` file, but i think there could be a bettere way

**Comment by jayaddison** [comment]
Ok, thank you - that makes sense and is good information.

To check my understanding: because we don't have support for `custom_js.html` in `grocy-docker`, it can lead to problems like this when trying to customize the application code running in the container (because it requires editing the docker files).

I'll read a bit more about #153 and `custom_js.html` soon.  I guess the reason that we cannot use [Docker volumes](https://docs.docker.com/storage/volumes/) for `custom_js.html` is that it's a single file, and it's in the `data` directory that is already a volume?

**Comment by barbax7** [comment]
Exactly, I edited `Dockerfile-grocy-frontend` in order to copy that file in data directory
Honestly I don't know how docker and grocy-docker properly work, but I figured out that it uses 3 volumes, where one is `grocy-docker_app-db`. In this one there is all the datas of `data` directory. We need a way to copy some custom files to this volume, as it is done for other files and directories
