### ISSUE TITLE
Error running docker-compose pull GROCY_IMAG_TAG variable is not set

### ISSUE THREAD

**Issue by fhold** [grocy/grocy-docker#159]
trying to install the container via the quick start guide I get the following error after the command:

`sudo docker-compose pull`

```
WARNING: The GROCY_IMAGE_TAG variable is not set. Defaulting to a blank string.
```
What am I doing wrong?

**Comment by jayaddison** [comment]
@fhold hmm.. I'm uncertain what went wrong there - could you try running `env | grep -w GROCY_IMAGE_TAG` to inspect what the value of the environment variable is (if set)?

**Comment by fhold** [comment]
@jayaddison thanks for responding! the output is the following `GROCY_IMAGE_TAG=v3.1.3-1`
FYI I run the docker-compose pull command as sudo.

**Comment by jayaddison** [comment]
@fhold ah, ok!  I think you should be able to run `docker-compose` without `sudo`, that may explain the problem.  Running sudo, leads to the creation of a separate sub-shell that does not have the environment variable set.

**Comment by fhold** [comment]
mhh that will bring me other errors :-( . Any other idea how I can use the script with sudo, can I hardset the variable?

**Comment by fhold** [comment]
issue can be closed - i used the install of linuxserver.io and that worked for me. Anyway thanks for helping out!
