### ISSUE TITLE
config.php step missing in documentation?

### ISSUE THREAD

**Issue by DerfOh** [grocy/grocy-docker#161]
Unable to run grocy: config.php in data directory (/var/www/public/../data) not found. Have you copied config-dist.php to the data directory and renamed it to config.php?

I get the above error when accessing my container. Did I miss something in the readme?

**Comment by DerfOh** [comment]
So I got it to work, my issue was modifying the volume to be 

      - `/home/derfoh/data/app-db:/var/www/data`

`root@virt-ubuntu-3:/# find . -name app-db`

This leads to another question: where does grocy save it's data? I can't find app-db anywhere on my filesystem. Is there a way to specify a location for the app-db for backup and recovery purposes?

**Comment by vnmabus** [comment]
I looked through the Docker documentation for volumes and found that by default in my Ubuntu there where in `/home/<my_user>/docker/root/volumes`.

Thus you can see (and copy or edit when the service is down) your data in `/home/<my_user>/docker/root/volumes/grocy-docker_app-db/_data/`.

**Comment by jayaddison** [comment]
Hi @DerfOh - I'm glad that you were able to sort out the `config.php` problem!

To help explain: the [`grocy/backend` image](https://hub.docker.com/r/grocy/backend) has the [default Grocy configuration built into it](https://github.com/grocy/grocy-docker/blob/1334b3f8c88157abd2ca6a3a451e7134fd204506/Containerfile-backend#L71) -- and the easiest way to modify the settings that the application runs with is to edit the [`grocy.env` file](https://github.com/grocy/grocy-docker/blob/1334b3f8c88157abd2ca6a3a451e7134fd204506/grocy.env) before (re)starting the containers.

To help track down where Docker volumes exist on a filesystem, I can recommend the [`docker volume inspect`](https://docs.docker.com/engine/reference/commandline/volume_inspect/) command which prints detailed metadata about volumes.
