### ISSUE TITLE
Which is the right prebuild docker image for what purpose ? 

### ISSUE THREAD

**Issue by guny74** [grocy/grocy-docker#165]
Hello,

there are a lot of prebuilt docker images 

- grocy/frontend 
- grocy/backend 
- groxy/nginx
- grocy/grocy

which should I user when ?

I want run grocy in a docker behind an nginx reverse proxy.

My first try with "linuxserver/grocy" + nginx was not successful.

Thank you

Regards

**Comment by jayaddison** [comment]
Hi @guny74 - selecting `grocy/frontend` plus `grocy/backend` is the correct combination today.

If you have `docker-compose` available, then you may run the containers directly by using the [`docker-compose.yml`](https://github.com/grocy/grocy-docker/blob/v3.3.0-0/docker-compose.yml) file.  Even if you do not, that file may still be a useful reference as it contains some of the configuration (environment variables, ports, volumes) required to run the containers.

As an explanation for the presence of four images: before the release of v3.1.0, the container names were updated; `grocy/nginx -> grocy/frontend` and `grocy/grocy -> grocy/backend` (#133).  As far as I know, Docker Hub doesn't (yet?) provide an ability to indicate that images are deprecated (see docker/hub-feedback#907), but I {would do that if / will do that when} possible for the old image names.

**Comment by guny74** [comment]
Hi, @jayaddison 

thank you for the information. I see now, that your images are for amd64, so I do ist at rpi4, so the choice of "linuxserver/docker-grocy" would be right.

But I have still an problem to connect via an nginx reverse proxy. 

So I will search further to an solution.

**Comment by jayaddison** [comment]
Ok, good luck!

The latest `grocy/frontend` and `grocy/backend` images are built for both `amd64` and also `arm64` -- but I admit I haven't tested the ARM64 version on an RPi.
