### ISSUE TITLE
Cannot build custom images due to DNS resolution failure

### ISSUE THREAD

**Issue by hexadecagram** [grocy/grocy-docker#179]
Hello,

I need to have the Grocy frontend and backend communicating over a port other than 9000. In order to accomplish this I need to clone this repo and modify static/backend/www.conf and static/frontend/common.conf. When I run `docker-compose build`, however. I get an error when the `wget ${GROCY_RELEASE_KEY_URI}` line in each Dockerfile is reached:

> Resolving berrnd.de (berrnd.de)... failed: Try again.
> wget: unable to resolve host address 'berrnd.de'

When I run wget on the exact same URL from the exact same shell with the exact same environment that I run `docker-compose build` in, the key is downloaded.

Another interesting thing is that the backend Dockerfile succesfully gets a file from getcomposer.org before this line is reached!

I have tried contacting the Docker IRC channel for help. I was first instructed to try restarting dockerd, which had no effect. I have also tried adding `dns: ["8.8.8.8"]` to /etc/docker/daemon.json and restarting. It too had no effect.

The host is running Docker 20.10.17 on ArchLinux. Could it be that I am using systemd-resolved and /run/systemd/resolve/stub-resolv.conf? Any other ideas what could be causing this?

**Comment by hexadecagram** [comment]
The `wget` line is run after switching to the www-data user. If I add in an additional `RUN wget ${GROCY_RELEASE_KEY_URI}` line, berrnd.de never resolves, no matter where I insert it, before or after the user switch. Just about any other method of visiting that URL works, so long as it doesn't happen in `docker-compose build`.

**Comment by jayaddison** [comment]
@hexadecagram can you create a minimal `Containerfile` / `Dockerfile` where the DNS failure occurs?  (either starting from scratch, or by removing every line from the file here until the error stops occurring)

**Comment by damianb** [comment]
Bizarrely experiencing this as well.  Added an `apk add bind-tools` and am running `dig berrnd.de A` only for it to come back with a perfectly intact A record.  But...wget throws `wget: unable to resolve host address 'berrnd.de'` immediately after.

wget on the host system works just fine.  I decided to drop down to something simpler - I ran just straight `alpine`, installed `bind-tools` and `wget`, ran the `dig` again (which was fine), and ran `wget` which failed exactly the same way.

And so I tried `curl`.  It too fails to resolve, bizarrely enough.  Exact same tests also fail on another system.

**Comment by damianb** [comment]
Got it.

Looking in DNS server logs, I see `AAAA` DNS requests going out and coming back with SERVFAIL responses for `berrnd.de`.

Running `wget -4 https://berrnd.de/data/Bernd_Bestel.asc` works just fine to retrieve the file.

**Comment by hexadecagram** [comment]
Also confirming that modifying Containerfile-(back|front)end to use `wget -4` results in successful image builds!

**Comment by berrnd** [comment]
> Looking in DNS server logs, I see `AAAA` DNS requests going out for `berrnd.de` and coming back with `SERVFAIL` responses.

Kind of unrelated to anything grocy, but thanks for noticing this - fixed that just now.

Interesting that this was a problem, none of my servers are currently reachable via IPv6 and therefore no domain has an `AAAA` record...

**Comment by jayaddison** [comment]
Nice, good find.  Opened #180 with a potential fix here.  `getcomposer.org` also seems to lack IPv6 when I attempt to make web requests to it, so I've added the `-4` option to `wget` there too.

**Comment by jayaddison** [comment]
> Interesting that this was a problem, none of my servers are currently reachable via IPv6 and therefore no domain has an AAAA record...

That's unusual.  Reading the `wget` documentation, it should attempt both IPv6 and IPv4 as a fallback if DNS responds with both formats of address.

So I suppose in this case a DNS resolver somewhere must have been responding with _only_ an IPv6 address? (despite an `AAAA` record not 'officially' existing?)

**Comment by jayaddison** [comment]
(...or the `SERVFAIL` response was confusing `wget` perhaps?  @hexadecagram - are you able to build successfully now _without_ the suggested fix from #180?)

**Comment by hexadecagram** [comment]
@jayaddison Yes, interestingly, I can build successfully *without* #180 now. It seems @berrnd "fixed that just now". If I may ask, what was done to fix it? I'm guessing DNS was configured to return something other than SERVFAIL for the AAAA record?

> Nice, good find. Opened #180 with a potential fix here. `getcomposer.org` also seems to lack IPv6 when I attempt to make web requests to it, so I've added the `-4` option to `wget` there too.

Resolving getcomposer.org was never an issue for me. If I had to guess, it was because it was not returning SERVFAIL.

> That's unusual. Reading the `wget` documentation, it should attempt both IPv6 and IPv4 as a fallback if DNS responds with both formats of address.

The man page explicitly states that the `-4` and `-6` options to `wget` will "force *connecting* to IPv4 or IPv6 addresses." It goes on to say that each switch will *additionally* force AAAA or AA resolution but the description makes it clear that the primary purpose of those options is to specify which protocol is used for *connecting.*

According to my interpretation of the man page, `wget` will *only* try both address families if *both record types* are returned during resolution. Evidence of this is as follows. When I run `wget` **from the shell** with the `-6` option and the berrnd.de URL, it fails. `-4` succeeds.

Looking at the `wget` man page, I think the `--prefer-family=IPv4` option is the correct one to be using. It seems this option has more to do with DNS resolution than connections. And in my case, *both* `--prefer-family=IPv4` and `--prefer-family=IPv6` succeed when run from the shell. But ...

> So I suppose in this case a DNS resolver somewhere must have been responding with _only_ an IPv6 address? (despite an `AAAA` record not 'officially' existing?)

Could be me. While I have AAAA resolution enabled for my network, I do not actually route IPv6 traffic across my firewall (yet). I do, however, have Docker configured to use IPv6 addressing (`"ipv6": true, "fixed-cidr-v6": "..."` in daemon.json), so there's that too.

It seems to me that if `wget` is now working with @berrnd's fix, there should be no need to patch the Containerfiles; users should always be able to rely on defaults.

**Comment by jayaddison** [comment]
Ok, yep.  Is the theory:

- Client configured with IPv6-precedence-over-IPv4 for DNS lookups
- `AAAA` lookup performed by client
- `SERVFAIL` response from DNS server
- Result: name resolution by client fails (despite the presence of a valid `A` record)

?

(...seems plausible, and would explain why the fix helped.  the client should have been an Alpine Linux base image)

**Comment by berrnd** [comment]
> If I may ask, what was done to fix it? I'm guessing DNS was configured to return something other than SERVFAIL for the AAAA record?

It was a configuration problem on my side, can't say exactly since when, maybe about 6 weeks or so.

I self-host the authoritative nameservers for all my domains using [dnsdist](https://dnsdist.org/) for the "frontend". There was  never a `AAAA` record published for any of my domains. I've changed some rules at that date which lead dnsdist to respond with [`DNSRCode.NOTIMP`](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6) for any `AAAA` query (instead of just an empty response when there is no record; that's the case now again).

I guess it's just like @jayaddison already mentioned above, due to the error response for the (first) `AAAA` query, `wget` doesn't do the additional `A` lookup. This seems to be however not the standard behavior of all DNS resolvers, otherwise my whole network would have been kind of offline since then (which I would have noted a little faster I guess)...

**Comment by hexadecagram** [comment]
> * Client configured with IPv6-precedence-over-IPv4 for DNS lookups

I have not *knowingly* set any precedence of IPv6 over IPv4 (or vice-versa).

The particular machine on which I'm running `docker-compose build` is using systemd-resolved with default settings. I am currently in the process of migrating my DNS servers to a ISC BIND master/slave configuration. For a number of reasons, I have had to set up something intermediary, which is shoestringed together with one `dnsdist` talking to another `dnsdist` which in turn talks to `dnsmasq` which resolves my LAN and finally talks to `unbound` which queries global DNS.

Fortunately, all of those components have default settings where resolution is concerned. It still could be any one of those components that has been affecting this but I have my doubts, as I would think it is exceptionally rare to prioritze AAAA over AA with no fallback by default.

However, the rest of the theory you describe is accurate, @jayaddison.

> I've changed some rules at that date which lead dnsdist to respond with [DNSRCode.NOTIMP (4)](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6) for any `AAAA` query (instead of just an empty response when there is no record; that's the case now again).

That would explain why `drill -t AAAA berrnd.de` shows an rcode of NOERROR now. I'm not sure what it said before but having it return NOTIMP instead seems to have done the trick.

> This seems to be however not the standard behavior of all DNS resolvers, otherwise my whole network would have been kind of offline since then (which I would have noted a little faster I guess)...

It seems most likely to me that the root of this issue lies with `wget`. The behavior that the man page seems to infer when *neither* the `-4` nor `-6` options are specified seems non-standard.

Thanks for the assistance with this. I think we've all benefited from a little DNSercize today. ;-)

**Comment by richfelker** [comment]
I just got a ping to chime in on this tracker thread. The stub resolver returning an error on ServFail (or NotImp, etc.) is the expected and intentional behavior. Anything else would allow DNSSEC validation bypass.

I'm not clear what the nameserver setup here is trying to achieve, but if it's trying to be a "v4 only" nameserver by intentionally making AAAA lookups ServFail/NotImp, that's wrong. These error responses will not cause the stub resolver to conclude that there is no v6 address, but rather that the nameserver is broken or unable to obtain trusted answers (e.g. due to attack). If you really insist on "blocking" v6 this way, NODATA or NxDomain (depending on whether the name exists at all) is the right response to use, but really you should not be doing this at the DNS level. If you want a v4-only network, just don't have any v6 interfaces or turn v6 off entirely, and let the AAAA lookups succeed but not get used.

**Comment by jayaddison** [comment]
Thanks @richfelker!  (that was me pinging - basically to rule out the possibility that this was some kind of unusual `musl` edge-case, as your comment does)

**Comment by berrnd** [comment]
> I'm not clear what the nameserver setup here is trying to achieve, but if it's trying to be a "v4 only" nameserver by intentionally making AAAA lookups ServFail/NotImp, that's wrong.

That was indeed the intention, but not for the authoritative domains, only for everything else (I use the same dnsdist "frontend" also as my private recursor). It was wrong and shouldn't have affected authoritative queries. `NXDOMAIN` most likely has the same effect, not sure about `NODATA`.

Background why I want(ed) to do this: Even when not having any IPv6 interface, practically just like always an `AAAA` lookup happens first. Just not resolving this query make various things noticable faster.

> I think we've all benefited from a little DNSercize today. ;-)

Yes - and it has confirmed once again that it's always DNS... :D
