### ISSUE TITLE
Remove Hardcoded VOLUME in Frontend Dockerfile for Nginx

### ISSUE THREAD

**Issue by RedlineTriad** [grocy/grocy-docker#189]
In the Dockerfile for the frontend Nginx container, it hardcodes a volume for access logs:
https://github.com/grocy/grocy-docker/blob/fba66410274169ffc1b59c74b520ea6da1e34cc1/Containerfile-frontend#L54

I want to run this myself, and I configured the container to log to stdout instead, since that is best practice for containers:
```nginx
error_log /dev/stdout info;

http {
  access_log /dev/stdout;
}
```
<details> 
  <summary>I also did this for the backend btw</summary>
  <h6>/etc/php8/php-fpm.d/z-php-fpm.conf</h6>
  <code>
[global]

error_log = /proc/self/fd/2
  </code>
</details>

However, since it is configured in the Dockerfile, there is no way to disable the creation of a volume.
If I don't mount anything there it just creates it as an anonymous volume, which is very annoying.

I would be willing to create a PR for this.

**Comment by RedlineTriad** [comment]
In general I would be really glad if logging exclusively used standard out, since otherwise you have to worry about log rotation, and log ingestion becomes way harder.

**Comment by jayaddison** [comment]
Sure, that makes sense - logging to stdout/stderr for containers does seem fairly standard, and fewer volumes to manage is generally going to result in a simpler system to operate.

It seems like there could be some competing requests at some point (for example, people requesting a way to backup logs) -- more information about use cases could be valuable if & when that happens.

> I would be willing to create a PR for this.

That'd be welcome, thank you.

**Comment by RedlineTriad** [comment]
Just for confirmation, I would just be doing a PR to remove the VOLUME, and would create a separate issue for stdout logging.
