### ISSUE TITLE
Separate Docker Hub Repositories for grocy and custom nginx

### ISSUE THREAD

**Issue by pixelyo** [grocy/grocy-docker#2]
with the current docker hub setup the one [repository](https://hub.docker.com/r/grocy/grocy-docker/tags/) is being overused. there should be two different repositories for grocy and the custom nginx image.

the setup could look like this:

```
grocy/grocy
grocy/nginx
```

this way one can also use the latest tag for the two images

here an example for the separation: [docker-compose](https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml) | [docker hub](https://hub.docker.com/r/mailcow/)

**Comment by pixelyo** [comment]
recklessnl: i see your point, it would be more comfortable to just have one container in total.

But even the current grocy-docker setup uses two different images. The docker hub repository is just being misused: Two different images are being stored in the same repository. The tags should be used for versions or slightly different builds of the same image but not for the separation of two different images.

**Comment by talmai** [comment]
It is generally recommended that you separate areas of concern by using one service per container. And while we could easily integrate everything within a single container, to get the most benefit out of Docker, it is generally recommended to avoid one container being responsible for multiple aspects of the overall application. We are connecting everything by leveraging the docker-compose file.

Besides: do we expect different versions of nginx anytime soon? It seems as if nginx would only update when there is a significant nginx update (unrelated to grocy).

**Comment by talmai** [comment]
>  The tags should be used for versions or slightly different builds of the same image but not for the separation of two different images.

@berrnd If this does change, I'll need you to create another repo just for nginx. I'm unconvinced atm that this will be needed, but consider this a heads-up.

**Comment by berrnd** [comment]
Do you mean the tag name format? This will stay for sure like it is now - `v<Major>.<Minor>.<Patch>`. The latest tag will always be the current stable version, the master branch is where the development is going on.

**Comment by recklessnl** [comment]
@talmai I have to disagree - why don't you look at Linuxserver docker images? Most of their apps have bundled SQlite databases or nginx servers. Why run dozens of containers when a single one can contain it just fine. 

It would be much preferred to have one single docker image that contains everything Grocy needs to run. This is what Docker containers are for in the first place, so you don't have to install and maintain all these dependencies.

**Comment by talmai** [comment]
> It would be much preferred to have one single docker image that contains everything Grocy needs to run.

with the caveat of "if all the user is running is grocy"...

For a practical example: I run grocy along with a series of other containers, and they are all mapped/proxied by a single container ([running jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy)). 

But, to be fair, take a look at additional arguments in favor of "separation of concerns" -> [this](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container) and [this](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#dont-install-unnecessary-packages) ['Decouple applications' section]

**Comment by recklessnl** [comment]
I really don't see the point of that when it's only nginx that you need - it's lightweight. It doesn't need a seperate container at all. Seems like you just won't listen, but the fact of the matter is all the biggest and most popular docker images condense most of the additional lightweight requirements (like php, nginx, etc) to make it easier for users. Running multiple containers that are dependent on eachother completely defeats this purpose.

At the very least, give these users the option to run it as a single container.

**Comment by talmai** [comment]
> Seems like you just won't listen

The links I provided are not written by me.

> At the very least, give these users the option to run it as a single container.

This seems like a easy compromise. Feel free to open a PR, and we can let both worlds coincide.

**Comment by recklessnl** [comment]
I just tried but I don't have another branch that I can compare it to in order to open a PR. I figured this thread would be enough to get this going and condense nginx into a single container. Not sure if you're a Dev but perhaps you could give it a go?

**Comment by pixelyo** [comment]
this issue got a little off topic. I think the images for grocy and the custom nginx shouldn't be combined. One can use docker-compose for easy setup which is already included. :)

linuxserver.io can surely combine the two if they want to.

---

> @talmai: It is generally recommended that you separate areas of concern by using one service per container. 

this is exactly the thing I want for the images and repositories. per image one repository. you can compare that with a github repository, where you use one repo per project.

---

> @berrnd: Do you mean the tag name format? This will stay for sure like it is now - v<Major>.<Minor>.<Patch>. The latest tag will always be the current stable version, the master branch is where the development is going on.

no, grocy needs a second docker hub repository. An additional one for the custom nginx image. The tags used in the current repo are messed up and misused to store different images in one repo.

**Comment by talmai** [comment]
> this is exactly the thing I want for the images and repositories. per image one repository. you can compare that with a github repository, where you use one repo per project.

no arguments against this (except for the question around "do we expect different versions of nginx anytime soon?"). But this only means that the nginx docker-hub-repo will have a single image. Not an issue.

@berrnd please give me a heads up when the new grocy-nginx dockerhub is ready, and I can update.

**Comment by berrnd** [comment]
@talmai I added you to the "owners" group of the grocy Docker Hub org - feel free to create/change anything what is needed. Do we also need a repo for that here on GitHub? If so, I also enabled that members of the grocy org here can create new repositories - so feel also free to add that when needed.

Thanks for your work! :)

**Comment by boardfish** [comment]
@talmai What extra config did you have to do to get grocy running from behind nginx-proxy? I'm hoping to run the same setup.

**Comment by jayaddison** [comment]
This issue is stale; the current situation is that `grocy-docker` builds two separate containers and provides a `docker-compose.yml` file to allow composition of these.

If anyone has further suggested improvements for build modifications, please provide a new issue with context and a plan for improvements, or ideally a pull request for discussion.

**Comment by jayaddison** [comment]
@pixelyo I'm preparing to package a new Docker Hub release for `grocy` and revisiting the concerns in this issue.

I'll add any further commentary and an associated pull request with any changes before performing the release.
