### ISSUE TITLE
Synology Diskstation Docker Install

### ISSUE THREAD

**Issue by gkron92** [grocy/grocy-docker#21]
Hi.  I've been trying for a day to get this to work and I can't figure it out.  I have Home Assistant (Hassbian not Hass.io) and HA-Bridge installed via docker so I have some experience doing this but I can't for the life of me figure out Grocy.  This is what it looks like in Synology docker.  

These are the images I downloaded:

![images](https://user-images.githubusercontent.com/50185681/60931313-1cdc6000-a287-11e9-8cce-798515742602.PNG)

This is what I have in the settings for the grocy container before launcing it as an example.  Is this even remotely correct?  When I launch the container nothing gets created in the web/grocy folder.  The web folder is synologys folder where you can access via a share and a webpage.  

![imagesettings](https://user-images.githubusercontent.com/50185681/60931408-82305100-a287-11e9-9c5a-4212377cca2b.PNG)

There is a separate container for nginx as well.  What should go in those settings?  When I try to launch the nginx container it stops immediately.  I see this in the log.  nginx: [emerg] host not found in upstream "grocy" in /etc/nginx/common.conf:20.   The port is 9000 by default and I get err connection refused after launching the container when trying to access through a browser.  I'm clearly lost.  Does anyone have a set of synology instructions?  Thanks for any help

**Comment by berrnd** [comment]
I've moved this to [grocy/grocy-docker](https://github.com/grocy/grocy-docker/)...

**Comment by Rayregula** [comment]
@gkron92 I'm not using docker through synology but have been having trouble figuring out how to get grocy working through docker for the last few days and have seen the same error on the nginx version that you mentioned. as for the normal grocy/grocy-docker:grocy version I think my issue may have something to do with it not building correctly as in the readme is says to use "docker-compose pull # if you haven't pulled or built" however for me docker says that "docker-compose" is not a recognized command and I feel like I've run out of things to try. Also haven't been able to get anything showing in volume I created for it (assuming I did it right) using "-v /home/docker/grocy:/config"

Jason

**Comment by gkron92** [comment]
I actually switched to Hass.io using this package.

https://community.home-assistant.io/t/hass-io-on-synology-dsm-native-package/125559/23

And then installed grocy using this.  Not ideal but up and running.  The docker install should be fixed or made a lot easier. 

https://community.home-assistant.io/t/community-hass-io-add-on-grocy/112422

**Comment by Rayregula** [comment]
I'll take a look at it when I get a chance, thanks.

**Comment by HydrelioxGitHub** [comment]
I've the same issue. ERR_CONNECTION_REFUSED after running the container.

**Comment by jayaddison** [comment]
@gkron92 Although that's not ideal, it sounds like you found a workaround.  Unfortunately I don't have access to Synology, and I'm unsure we can easily test or reproduce the problem.

If anyone's able to provide repro steps that don't require Synology -- or know of another way to further investigate the issue here, we can look into it further.

**Comment by gkron92** [comment]
I installed via docket.  All good
