### ISSUE TITLE
Update guide incomplete.

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy-docker#219]
According to the documentation [here](https://github.com/grocy/grocy#how-to-update), in some instances, the data/viewcache should be emptied and after the starting of the container, the root route should be called first to execute migrations. It would be nice if that is stated in the update guide here in this repo.

**Comment by jayaddison** [comment]
Closing as this should be handled by #217 soon.

More detail: there's a decent amount of context to read in #217, but the short version is: the [suggested (and now accepted) approach](https://github.com/grocy/grocy-docker/issues/217#issuecomment-1666457420) is that we can use `tmpfs` to hold the `viewcache` directory in our containers; that means that the contents will be ephemeral, and there won't be a need to clear it during upgrades.
