### ISSUE TITLE
Can't add item on first login

### ISSUE THREAD

**Issue by improvethings** [grocy/grocy-docker#237]
![Screenshot from 2024-02-08 11-40-28](https://github.com/grocy/grocy-docker/assets/16601027/92597062-59af-4ab1-aeb2-338a30a437e9)

As you can see from the screen shot, when I click "Add Item" on first login under "Shopping list", the popup modal is all white with just a close button. Same thing happens when I choose "New shopping list".

**Comment by berrnd** [comment]
Duplicate of #https://github.com/grocy/grocy/issues/2421.
