### ISSUE TITLE
Unable to set custom domain for grocy in Android app

### ISSUE THREAD

**Issue by tetra-archos** [grocy/grocy-docker#241]
I am using cloudflared access tunnels to access grocy, however my default domain is still my local IP, when using the grocy app I am unable to set the custom servername to have it redirect through cloudflare. Can you add the feature to support custom URLs in the android app? or explain how I can configure grocy to use the domain I have setup through cloudflare.

**Comment by berrnd** [comment]
The community contribute android app is not maintained here and this is also neither Cloudflare support.
