### ISSUE TITLE
HTTP 400 Request header too large

### ISSUE THREAD

**Issue by dUc0N** [grocy/grocy-docker#25]
I've installed Grocy inside Docker, but every time I try to access it, I get an HTTP 400 "Bad Request" page with the error "Request Header Or Cookie Too Large." I can work around this by manually removing all my stored cookies for that host, but that's a pain to do every time. The problem occurs just the same over HTTP or HTTPS.

I found some help online for nginx generally, but do you know of a quick way to increase the allowed header size in the nginx container? Alternatively, is there any way to fix it in the repo so that this isn't an issue for anyone else?

**Comment by talmai** [comment]
> Alternatively, is there any way to fix it in the repo so that this isn't an issue for anyone else?

I can't replicate this at all. Can you detail how you are running this?

**Comment by dUc0N** [comment]
I've got Grocy running inside of a docker container alongside portainer and grafana; that's probably part of the problem and why I had so many cookies. It's more of a nuisance than anything else. I'm working this weekend, but afterwards I can probably make some time to gather any more information you need to replicate the problem.

In the meantime, I worked around it by changing these lines in /etc/nginx/nginx.conf inside the running container:

client_max_body_size 5M;
large_client_header_buffers 50 1k;

**Comment by prankousky** [comment]
I have the same problem. Steps:

* git clone the repo
* edit `docker-compose.yaml`
* `docker-compose build`
* `docker-compose up`

I get the exact same error. My modified `docker-compose.yaml` looks like this; I had to change the ports...

```
# Usage:
# docker-compose build && docker-compose up
version: '2'

services:
  grocy-nginx:
    image: grocy/grocy-docker:nginx
    build:
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '2080:80'
      - '2443:443'
    volumes_from:
      - grocy
    container_name: grocy-nginx

  grocy:
    image: grocy/grocy-docker:grocy
    build:
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - 9000
    volumes:
      - /home/me/docker/grocy/conf:/www
    environment:
      PHP_MEMORY_LIMIT:     512M
      MAX_UPLOAD:           50M
      PHP_MAX_FILE_UPLOAD:  200
      PHP_MAX_POST:         100M
      GROCY_CULTURE: de
# added those lines after reading dUc0N's post here, but no difference...
# those lines weren't there initially, I just added them because I thought I'd perhaps be able to pass on those values via environment...
      CLIENT_MAX_BODY_SIZE: 5M
      LARGE_CLIENT_HEADER_BUFFERS: 50 1k
    container_name: grocy
volumes:
  database:
```

It did create `/home/me/docker/grocy/config/public` (so the folder `public`, as the subfolders were previously created by me). This folder is empty.

I had grocy running just fine on that same machine and via docker before; however, back when I created it, I didnt' care about https, so I didn't enable it. Now that I am trying to run it, it won't work at all. The output from `docker-compose up` (as I didn't flag it `-d` is

```
grocy                      | [02-Jan-2020 10:25:20] NOTICE: fpm is running, pid 1
grocy                      | [02-Jan-2020 10:25:20] NOTICE: ready to handle connections
```

That is all. I don't get an error in my log when I browse `https://host:2443/grocy` or `http:ip:2080/grocy` (nor when browsing those urls without `/grocy`). While the browser displays that error, the log says nothing.... Please help :)

![grafik](https://user-images.githubusercontent.com/11297070/71662873-4d431980-2d53-11ea-9bab-955249bd0e14.png)

**Comment by jayaddison** [comment]
This isn't a problem that can be truly solved by the `grocy` nor `grocy-docker` codebases, since it occurs in environments where a single domain name / host is being shared by multiple web applications.

Where possible, unique host / domain names should be used for each web application so that unrelated cookies aren't accidentally shared; that can result in overly-large request header sizes as apparent here, and other issues.
