### ISSUE TITLE
Build failures relating to lastversion and/or apk cache clearance

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy-docker#30]
Hi

The build fails sometimes on Travis when grabbing the latest version or cleaning cache apk.

Best regards

**Comment by jayaddison** [comment]
@BlueBlueBlob do you have an example Travis build log?  I've been investigating some failures due to GitHub rate-limiting as part of #39 and would be interested to find out of this is related.

**Comment by BlueBlueBlob** [comment]
Sure. Tomorrow.
Because mis

**Comment by BlueBlueBlob** [comment]
And thx to take care 👍

**Comment by BlueBlueBlob** [comment]
Hi,

[log.txt](https://github.com/grocy/grocy-docker/files/4386949/log.txt)

**Comment by jayaddison** [comment]
@BlueBlueBlob Ok, yep!  I do think those failures may be caused by GitHub rate limiting.  Looking at  line 542 of your logs:

```
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 11, in <module>
    load_entry_point('lastversion==0.2.4', 'console_scripts', 'lastversion')()
  File "/usr/lib/python2.7/site-packages/lastversion/lastversion.py", line 400, in main
    args.shorter_urls)
  File "/usr/lib/python2.7/site-packages/lastversion/lastversion.py", line 238, in latest
    the_date = r_commit.json()['committer']['date']
KeyError: 'committer'
```

Here's the [code](url) in `lastversion` where this happens -- it's after a GET request to the GitHub API, and if they'd returned a rate-limit response it wouldn't contain a 'committer' (hence the `KeyError`).

I think #39 should help out.  If you'd like to try it out, a GitHub API token with `read:packages` scope added as an [encrypted variable](https://docs.travis-ci.com/user/encryption-keys#usage) for `GITHUB_API_TOKEN` should do the trick :)

**Comment by jayaddison** [comment]
PS: Please note that #39 will only help during retrieval the latest version of `grocy` using `lastversion` and other GitHub-related actions; the `apk` cache clearing is unrelated to GitHub and will need a bit more investigation.

**Comment by BlueBlueBlob** [comment]
> PS: Please note that #39 will only help during retrieval the latest version of `grocy` using `lastversion` and other GitHub-related actions; the `apk` cache clearing is unrelated to GitHub and will need a bit more investigation.

Thx I will try and send you log if apk cache error is still there.

For my point of view : if GitHub has rate limit, you should ask people to create a token. Because it will mess your others projects.

Thx again and keep in touch 👍

**Comment by jayaddison** [comment]
@BlueBlueBlob We should be in good shape here now I believe.  The following PRs have addressed these build concerns:

#39 - allows usage of a GitHub API token to prevent rate limiting
#42 - removed usage of the `apk` cache at build-time
#47 - remove the last reference to the `apk` cache from the build process

If you're still seeing this issue please comment with a hyperlink to the build logs on Travis-CI (i.e. `https://travis-ci.org/.../builds/...`)
