### ISSUE TITLE
create first user / admin

### ISSUE THREAD

**Issue by AntouanK** [grocy/grocy-docker#34]
Hi there.

I just cloned the repo and run the `docker-compose`
Apart from a small fix ( needed to add a `mkdir -p /var/tmp/nginx` in one of the Dockerfiles ) everything else ran fine.

So now the containers are up and I can see it at port 8080 ( I have something else running at 80 ).

My question is : 
- how do I create users and how do I admin the whole thing?
I've been looking the grocy repo and website, and I cannot find anything on that anywhere.

Any help?

All I can see at 8080 is this : 
![Screenshot from 2020-03-21 18-13-23](https://user-images.githubusercontent.com/4569111/77232162-aa56aa80-6b9f-11ea-9673-ff76377611b7.png)

**Comment by mittwinter** [comment]
When I clicked on Journal, I was presented with a login form and the default admin/admin from grocy worked. From there, I was able to create additional users.

**Comment by AntouanK** [comment]
That's what I needed, thank you.
Are those two simple steps explained anywhere? Couldn't find anything.

**Comment by talmai** [comment]
Valid points, but closing as this would belong to instructions on main Grocy repo. Pinging @berrnd as FYI.

**Comment by berrnd** [comment]
Answered in grocy/grocy#96.
