### ISSUE TITLE
In order to use this behind an additional reverse-proxy, I need an environment variable to overwrite the BASE_URL via docker

### ISSUE THREAD

**Issue by jhammons** [grocy/grocy-docker#4]
First and foremost, thank you all for creating this great piece of software. I thoroughly enjoy it and find it very useful.

I suppose the title of this suggests my problem. I am wanting to work on a pull request to use an environment variable to sed out the BASE_URL in config.php in the container so I can configure the BASE_URL before ever provisioning the container.

**Comment by jhammons** [comment]
@berrnd @talmai I have a pull request for this feature... and, if permitted to push it to the repository there are some other things I may be interested in adding in the near future. Any chance you can give me access to push a pull request for your review? Thanks in advance.

**Comment by berrnd** [comment]
Creating a fork / pull request is the normal workflow - and not much different than creating a branch here, I think.

If it helps, I can also add to grocy that any setting in `config.php` is also checked first if there is an environment variable with the same name, and if so, the environment variable would take precedence. Would this help?

**Comment by talmai** [comment]
> If it helps, I can also add to grocy that any setting in config.php is also checked first if there is an environment variable with the same name, and if so, the environment variable would take precedence. Would this help?

I haven't see @jhammons PR, but if you do this, we can easily add env variables to the docker-compose.yml file as well. So end-user would only need to update it there.

**Comment by berrnd** [comment]
Will do this, will be tracked in grocy/grocy#118.

I would suggest to prefix all environment variables with `GROCY_` as [mentioned in the created issue](https://github.com/grocy/grocy/issues/118#issue-385804165).

**Comment by jhammons** [comment]
Ah, very well. Sorry, but I cannot create a new pull request. The option requires I select a branch, which of course I cannot submit. It's a chicken and egg problem as best as I can tell.
I agree the GROCY_ prefix makes sense and if you're keen, feel free to close this issue and I'll track and work on grocy/grocy#118 if I or we can figure out how. :)

**Comment by jhammons** [comment]
I suppose the only way I can submit my PR is if I fork it and create the pull request using that. Is that your preferred workflow?
Having said that, I agree the the grocy project and grocy/grocy#118 is a better way to accomplish this.

**Comment by berrnd** [comment]
(Off-Topic)
> I suppose the only way I can submit my PR is if I fork it and create the pull request using that. Is that your preferred workflow?

I think that's the normal way we all do such changes here... :D
https://guides.github.com/introduction/flow
https://gist.github.com/Chaser324/ce0505fbed06b947d962

Just create a new branch in https://github.com/jhammons/grocy-docker (or even push to master branch, but that's not the common way) and GitHub will show you a "Create Pull request" button right after you pushed your changes on your forks main repo page...

Thanks for your work/ideas on grocy-docker! :)

**Comment by aureooms** [comment]
Has this been fixed? How do I specify the base URL for this container?

**Comment by jayaddison** [comment]
Closing this as resolved / largely discontinued.

@aureooms Please see https://github.com/grocy/grocy/issues/118 and the `docker-compose.yml` for information regarding environment variables.
