### ISSUE TITLE
Unauthenticated users are not redirected to /login 

### ISSUE THREAD

**Issue by tet3** [grocy/grocy-docker#69]
This issue has come up a couple of other times - grocy/grocy#96 and [grocy-docker grocy/grocy#34](https://github.com/grocy/grocy-docker/issues/34). In those issues, Bernd has pointed out that they're only warnings, but this is a more serious issue, from both a usability and a security standpoint. **Unauthenticated users are not redirected to `/login` for 4 of the 9 possible values of the `ENTRY_PAGE` setting, including the shipped default, `stock`.** 

When you spin up a brand new grocy-docker image, it is in default/`production` mode because of the null `GROCY_MODE` environment variable in the [then-shipped `grocy.env`](https://github.com/grocy/grocy-docker/blob/d5163459e9211010167834254847eb62a8241fe2/grocy.env) . (All of the behavior documented below is the same if it's explicitly set to `production` as well.) If you spin it up and go to http://localhost, you are redirected to http://localhost/stockoverview, as `'stock'` is the default value for `ENTRY_PAGE` in the `config.php` that get's copied from `config-dist.php`. You get the "warning" about "undefined constant `GROCY_USER_ID`" because you're not logged in, and so `GROCY_USER_ID` hasn't been set! What **should** happen is that the user is redirected to http://localhost/login so that they can, well, log in. 

I tested all of the possible values for `ENTRY_PAGE` by setting `GROCY_ENTRY_PAGE` in `grocy.env`. 
The following values do **not** redirect the unauth'd user and show a partially rendered page with the  "undefined constant `GROCY_USER_ID`"  warning:

- stock
- chores
- batteries
- tasks

The following values work as expected — an unauthenticated user hitting the base URL is redirected to /login:

- shoppinglist
- recipes
- equipment
- calendar
- mealplan

What's interesting is that `stock`, `chores`, and `batteries` all correspond to an "overview" path, ie, the resulting URL is `/stockoverview`, `/choresoverview`, etc. `tasks` just sends the user to `/tasks`, but still doesn't redirect them to `/login`. 

I tested a few other/deeper URLs as an unauth'd user, and all those I tested redirected to /login, but it wasn't a comprehensive test:

- /products
- /product/3
- /locations
- /location/2
- /taskcategories
- /recipe/1

**Comment by jayaddison** [comment]
@tet3 Do you mind updating this issue description to link to `grocy.env` as-it-was when you opened the issue, just for anyone gathering context in future?

That should be https://github.com/grocy/grocy-docker/blob/d5163459e9211010167834254847eb62a8241fe2/grocy.env as best I can tell

(NB: it looks like I could technically edit your description myself but I figure it's probably best to edit our own comments & descriptions unless really necessary)

**Comment by jayaddison** [comment]
Currently investigating the root cause here.

**Comment by tet3** [comment]
Edited. While not understanding the root cause is always frustrating, since there seem to be other advantages to the work done on #67 and that fixes it, I'd just go with that, myself. :-) 
I got that branch up and running on my VPS last night, though I have to sort out why the SSL isn't working.

**Comment by jayaddison** [comment]
@berrnd I've nearly tracked down the cause here - certainly there's enough information that I can pinpoint a potential security issue in, and have a proposed fix.

The issue comes down to what content should be considered permissible for non-authenticated users to view.  In general for a production system it's likely sensible to deny read access (i.e. redirect to login before rendering any content) for non-authenticated users, since that seems to be the intent of the middleware code.

Although I've pinpointed a fix in the application code, I'm still digging further to determine why this particular pull request alters the behaviour.

**Comment by berrnd** [comment]
Thanks, I see - the rendered originally requested page is rendered in addition to the 302 redirect (browsers, including the developer tools, seem to not show the response body of a 302 response).

Should be easy to fix, I think we should do this immediately (today).

**Comment by berrnd** [comment]
We do this also already for the API, here:
https://github.com/grocy/grocy/blob/11bf89e13a7c0b356910a9a39514b80c0a6f2eb2/middleware/ApiKeyAuthMiddleware.php#L82

(Sorry for the off-topic comments...)

**Comment by berrnd** [comment]
I've created grocy/grocy#696 to track and fix the security issue - thanks a lot for finding that!
