### ISSUE TITLE
502 error when adding or editing quantities

### ISSUE THREAD

**Issue by WychWitch** [grocy/grocy-docker#93]
I'm running a docker of Grocy (specifically [this](https://github.com/linuxserver/docker-grocy) one, but I've tried [this](https://github.com/grocy/grocy-docker) one as well with the same issue) and I get a 502 error whenever I attempt to add or edit the types of quantities on the site. Adding or editing other types of things (locations, stores, products, etc) works perfectly fine, I'm only having trouble with quantities.

I used the default docker-file and docker-compose settings (literally only changed the timezone and <path-to-data>), and I have no idea what could be the problem.

Here's my server settings!
```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
```

Thanks for any help in advance!

**Comment by berrnd** [comment]
So seems to be Docker specific, so I'm moving this to grocy/grocy-docker...

A 502 error is probably something before the request hits PHP, so I would try to check the nginx logs if there is something interesting...

**Comment by WychWitch** [comment]
Thanks for the hint! Also thank you for moving it to the correct place.

I checked my nginx logs and this is what I found:

```
2020/05/08 04:19:04 [error] 1529#1529: *90844 connect() failed (111: Connection refused) while connecting to upstream, client: <ip address>, server: <URL>, request: "GET /api/system/db-changed-time HTTP/1.1", upstream: "http://127.0.0.1:9283/api/system/db-changed-time", host: "<URL>", referrer: "https://<URL>/stockoverview"
```
It looks like it might have something to do with the timezone?? which is weird

This is how I have it written in my dockerfile and docker-compose 
```
docker create \
  --name=grocy \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=CST \
  -p 9283:80 \
  -v /var/local/grocy:/config \
  --restart unless-stopped \
  linuxserver/grocy
```
Is this correct? Or is it something else entirely?

**Comment by jayaddison** [comment]
Hi @WychWitch - thanks for the issue report!  Apologies that it has taken a little while to respond.

I haven't been able to reproduce the problem you found using the `grocy/grocy` container image; did you edit `grocy.env` and run `docker-compose up` to make your changes, or perhaps another set of commands?

Although we don't maintain `linuxserver/grocy` here, I did notice that you used `TZ=CST` when running that container, and as far as I can tell, CST is not a [valid timezone for tzdata](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

If you try `TZ=US/Chicago` then that may have better results -- although I don't know whether that will resolve the quantity editing issue you've found.

If you can provide more details to reproduce this under `grocy/grocy` then I'll be glad to take another look.

**Comment by WychWitch** [comment]
Hello!! Thank you for getting back to me! Bizarrely, when I tried the `grocy/grocy` image again just to make sure I reproduced all of the steps, it decided to work! I'm not sure what could've changed, but maybe I hadn't properly configured grocy.env (i vaguely remember renaming it to .env, but I don't know if I'm thinking of something else)

Thank you again anyways! I'll close this issue now.

**Comment by jayaddison** [comment]
@WychWitch No problem, glad to hear that it worked.  Glad to hear of any other problems you run into, and/or comparison with the `linuxserver/grocy` container.

**Comment by WychWitch** [comment]
I'll let you know!! Thanks a lot
