### ISSUE TITLE
Running Grocy-Docker on AWS

### ISSUE THREAD

**Issue by verginer** [grocy/grocy-docker#95]
If anyone wants/attempts to run grocy on AWS as a docker image this is an important point.

For the docker port to be visible outside the EC2 instance, beyond setting up the correct Security Groups (i.e., HTTP and HTTPS), it is necessary to change the "localhost" ip to `0.0.0.0`.

Change in `docker-compose.yml` this

```yaml
    ports:
      - '127.0.0.1:80:8080'
      - '127.0.0.1:443:8443'
```

to this 

```yaml
    ports:
      - '0.0.0.0:80:8080'
      - '0.0.0.0:443:8443'
```

Hope this helps someone :)

**Comment by jayaddison** [comment]
Thanks @verginer!

Good news: this part of the process is now documented in a `grocy` [setup tutorial](https://github.com/grocy/docs/blob/f9f608edd32a0d2f793635715c2c5265305a011f/tutorials/setup.md#docker-container).

**Comment by jayaddison** [comment]
@verginer I think we should suggest only opening port 443 when making the application public - what do you reckon?  See #97 for some other notes.  HTTPS support during application setup from this repository & docker image isn't great at the moment.

**Comment by verginer** [comment]
Thanks @jayaddison for including this in the tutorial :).
I agree that HTTPS should be applied everywhere especially when on the open internet.

To avoid having warnings of self signed certificates it might be necessary to use letsencrypt to get an accepted certificate.

I am not an expert on this matter, but I will experiment with it.
[This post](https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) might be a first step.
