### ISSUE TITLE
Docker Hub Pull Fails

### ISSUE THREAD

**Issue by clarkburbidge** [grocy/grocy-docker#96]
I'm trying to get a docker version set up on Amazon EC2 a Amazon Linux AMI server.

"docker run hello-world" has succeeded.

[ec2-user@ip- ~]$ docker login
Authenticating with existing credentials...
Login Succeeded
[ec2-user@ip- ~]$ docker pull grocy/grocy
Using default tag: latest
Error response from daemon: manifest for grocy/grocy:latest not found: manifest unknown: manifest unknown

Also tried:
docker-compose pull
docker-compose up

So you know that I'm a docker n00b. I'm happy to add some documentation once I get it running.

**Comment by clarkburbidge** [comment]
Maybe docker hub is depreciated, but this worked:

https://github.com/grocy/docs/blob/master/tutorials/setup.md#docker-container

**Comment by raym** [comment]
I am also a docker n00b, but to me it looks like there is no `latest` tag, if you view the list of tags, you can copy the command to pull the latest version:
https://hub.docker.com/r/grocy/grocy/tags

As of this moment, this is the latest:
```
docker pull grocy/grocy:v2.7.1-3
```

**Comment by raym** [comment]
Even so, I think the repository needs to be cloned in order to run the `docker-compose` commands in the README.
